//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploadify.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uploadify.Client.Web.Resources.TranslationDictionary", typeof(TranslationDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string authorization_permissions_all {
            get {
                return ResourceManager.GetString("authorization.permissions.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage files.
        /// </summary>
        internal static string authorization_permissions_edit_files {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions.
        /// </summary>
        internal static string authorization_permissions_edit_permissions {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage roles.
        /// </summary>
        internal static string authorization_permissions_edit_roles {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string authorization_permissions_edit_users {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string authorization_permissions_none {
            get {
                return ResourceManager.GetString("authorization.permissions.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files.
        /// </summary>
        internal static string authorization_permissions_view_files {
            get {
                return ResourceManager.GetString("authorization.permissions.view_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View permissions.
        /// </summary>
        internal static string authorization_permissions_view_permissions {
            get {
                return ResourceManager.GetString("authorization.permissions.view_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View roles.
        /// </summary>
        internal static string authorization_permissions_view_roles {
            get {
                return ResourceManager.GetString("authorization.permissions.view_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View users.
        /// </summary>
        internal static string authorization_permissions_view_users {
            get {
                return ResourceManager.GetString("authorization.permissions.view_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploadify.
        /// </summary>
        internal static string common_app_name {
            get {
                return ResourceManager.GetString("common.app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string common_file {
            get {
                return ResourceManager.GetString("common.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string common_folder {
            get {
                return ResourceManager.GetString("common.folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation not found..
        /// </summary>
        internal static string common_translation_not_found {
            get {
                return ResourceManager.GetString("common.translation_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string components_authenticated_layout_about_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string components_authenticated_layout_dashboard_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string components_authenticated_layout_email_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string components_authenticated_layout_fullname_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.fullname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string components_authenticated_layout_logout_button {
            get {
                return ResourceManager.GetString("components.authenticated_layout.logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string components_authenticated_layout_management_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string components_authenticated_layout_more_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.more_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string components_authenticated_layout_privacy_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string components_authenticated_layout_profile_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string components_authenticated_layout_shared_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string components_files_dashboard_row_options_delete_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.delete_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string components_files_dashboard_row_options_detail_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.detail_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string components_files_dashboard_row_options_download_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.download_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string components_files_dashboard_row_options_hide_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.hide_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string components_files_dashboard_row_options_move_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.move_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string components_files_dashboard_row_options_open_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string components_files_dashboard_row_options_publish_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.publish_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string components_files_dashboard_row_options_rename_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.rename_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string components_files_dashboard_row_options_share_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.share_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        internal static string components_files_detail_contact_text {
            get {
                return ResourceManager.GetString("components.files.detail.contact_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string components_files_detail_created_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.created_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string components_files_detail_date_created_label {
            get {
                return ResourceManager.GetString("components.files.detail.date_created_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string components_files_detail_date_updated_label {
            get {
                return ResourceManager.GetString("components.files.detail.date_updated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string components_files_detail_delete_button {
            get {
                return ResourceManager.GetString("components.files.detail.delete_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string components_files_detail_download_button {
            get {
                return ResourceManager.GetString("components.files.detail.download_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string components_files_detail_download_label {
            get {
                return ResourceManager.GetString("components.files.detail.download_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size on disk.
        /// </summary>
        internal static string components_files_detail_drive_size_label {
            get {
                return ResourceManager.GetString("components.files.detail.drive_size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string components_files_detail_extension_label {
            get {
                return ResourceManager.GetString("components.files.detail.extension_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string components_files_detail_file_name_label {
            get {
                return ResourceManager.GetString("components.files.detail.file_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string components_files_detail_file_type_text {
            get {
                return ResourceManager.GetString("components.files.detail.file_type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items.
        /// </summary>
        internal static string components_files_detail_folder_items_count_label {
            get {
                return ResourceManager.GetString("components.files.detail.folder_items_count_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        internal static string components_files_detail_folder_name_label {
            get {
                return ResourceManager.GetString("components.files.detail.folder_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        internal static string components_files_detail_folder_type_text {
            get {
                return ResourceManager.GetString("components.files.detail.folder_type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string components_files_detail_location_label {
            get {
                return ResourceManager.GetString("components.files.detail.location_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME.
        /// </summary>
        internal static string components_files_detail_mime_label {
            get {
                return ResourceManager.GetString("components.files.detail.mime_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string components_files_detail_move_button {
            get {
                return ResourceManager.GetString("components.files.detail.move_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string components_files_detail_open_subfolder_label {
            get {
                return ResourceManager.GetString("components.files.detail.open_subfolder_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        internal static string components_files_detail_private_accessibility_text {
            get {
                return ResourceManager.GetString("components.files.detail.private_accessibility_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        internal static string components_files_detail_public_accessibility_text {
            get {
                return ResourceManager.GetString("components.files.detail.public_accessibility_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string components_files_detail_rename_button {
            get {
                return ResourceManager.GetString("components.files.detail.rename_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string components_files_detail_resource_type_label {
            get {
                return ResourceManager.GetString("components.files.detail.resource_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string components_files_detail_share_button {
            get {
                return ResourceManager.GetString("components.files.detail.share_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string components_files_detail_shared_label {
            get {
                return ResourceManager.GetString("components.files.detail.shared_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string components_files_detail_size_label {
            get {
                return ResourceManager.GetString("components.files.detail.size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string components_files_detail_user_created_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.user_created_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string components_files_detail_user_updated_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.user_updated_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string components_files_dialogs_create_files_tab {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.files_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string components_files_dialogs_create_folders_tab {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.folders_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string components_files_dialogs_create_name_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string components_files_dialogs_create_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string components_files_dialogs_create_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to move the file to the recycle bin? The file can be restored for 7 days after deletion, after that the change will be irreversible..
        /// </summary>
        internal static string components_files_dialogs_delete_description {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string components_files_dialogs_delete_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move folder to recycle bin.
        /// </summary>
        internal static string components_files_dialogs_delete_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        internal static string components_files_dialogs_move_folder_select_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.folder_select_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string components_files_dialogs_move_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change location.
        /// </summary>
        internal static string components_files_dialogs_move_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string components_files_dialogs_rename_name_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string components_files_dialogs_rename_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string components_files_dialogs_rename_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_file_too_large {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.file_too_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload is limited to 50 files at the same time.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_too_many_files {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.too_many_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} upload failed.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_uplaod_failure {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.uplaod_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} upload was successful.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_uplaod_success {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.uplaod_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permissions to the role to ensure the proper functioning and security of your system. Each role can have a different set of permissions that define what users can do with that role. Select only those permissions that correspond to the responsibilities and requirements of the role..
        /// </summary>
        internal static string components_permission_assignment_description {
            get {
                return ResourceManager.GetString("components.permission_assignment.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permission.
        /// </summary>
        internal static string components_permission_assignment_submit_button {
            get {
                return ResourceManager.GetString("components.permission_assignment.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign permission.
        /// </summary>
        internal static string components_permission_assignment_title {
            get {
                return ResourceManager.GetString("components.permission_assignment.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string components_permission_dashboard_date_updated_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.date_updated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string components_permission_dashboard_edit_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.edit_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string components_permission_dashboard_role_detail_title {
            get {
                return ResourceManager.GetString("components.permission_dashboard.role_detail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string components_permission_dashboard_role_name_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.role_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission overview.
        /// </summary>
        internal static string components_permission_dashboard_title {
            get {
                return ResourceManager.GetString("components.permission_dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated by.
        /// </summary>
        internal static string components_permission_dashboard_user_updated_by_username_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.user_updated_by.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string components_permission_selector_label {
            get {
                return ResourceManager.GetString("components.permission_selector.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string components_role_selector_label {
            get {
                return ResourceManager.GetString("components.role_selector.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, this dissertation will review strategies for deploying applications effectively, including the use of modern tools and platforms such as Docker. In this way, this thesis demonstrates that even within individual academic research, significant progress and innovation can be achieved, often overlooked in larger, commercially driven projects. The thesis thus offers a fresh and comprehensive perspective on information technology, highlighting the potential for deep professional understanding and practic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_fifth {
            get {
                return ResourceManager.GetString("pages.about.sections.fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the modern, ever-changing world of information technology, attention is often directed towards large-scale projects developed by large teams. Nevertheless, this bachelor thesis takes a direction that emphasizes the significance of individual contribution and innovation. The goal is to create a project that is not constrained by conventional licensing constraints, and instead offers a solution under an MIT or lesser GNU license, encouraging free access and wider application in the academic and development [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_first {
            get {
                return ResourceManager.GetString("pages.about.sections.first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particular attention is also devoted to WASM, as one of the four natively supported languages in the browser, exploring its capabilities and integration in .NET, especially through tools such as Blazor. The work also emphasizes the significance of rigorous unit testing in .NET, highlighting the necessity of software reliability and resilience..
        /// </summary>
        internal static string pages_about_sections_fourth {
            get {
                return ResourceManager.GetString("pages.about.sections.fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose is also to deepen expertise and proficiency in .NET technology, with an emphasis on creating a robust project structure. Within this, the project will focus on layered architecture, including domains, data, core, application, RESTful APIs and other key components. Significant effort is given to security considerations, including advanced security measures such as the implementation of OAuth2 and OpenID Connect standards, password hashing and authentication, and defenses against common security t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_second {
            get {
                return ResourceManager.GetString("pages.about.sections.second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The innovation of design patterns is another crucial point, and the work will not be focused on traditional approaches, but will incorporate advanced patterns such as CQRS and patterns such as dependency injection, representing a significant departure from conventional approaches. In the area of RESTful APIs, the thesis will not only focus on fundamental implementations, but also introduce the OpenAPI specification and explore the possibilities of data caching and request rate limiting..
        /// </summary>
        internal static string pages_about_sections_third {
            get {
                return ResourceManager.GetString("pages.about.sections.third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string pages_about_title {
            get {
                return ResourceManager.GetString("pages.about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string pages_dashboard_title {
            get {
                return ResourceManager.GetString("pages.dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has been made private.
        /// </summary>
        internal static string pages_dashboard_visibility_changed_failure {
            get {
                return ResourceManager.GetString("pages.dashboard.visibility_changed.failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has been published.
        /// </summary>
        internal static string pages_dashboard_visibility_changed_success {
            get {
                return ResourceManager.GetString("pages.dashboard.visibility_changed.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File details.
        /// </summary>
        internal static string pages_detail_title {
            get {
                return ResourceManager.GetString("pages.detail.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and rapid setup of permissions for your application..
        /// </summary>
        internal static string pages_management_description {
            get {
                return ResourceManager.GetString("pages.management.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define various tiers of access and assign permissions according to the requirements of your application..
        /// </summary>
        internal static string pages_management_permissions_description {
            get {
                return ResourceManager.GetString("pages.management.permissions.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions .
        /// </summary>
        internal static string pages_management_permissions_label {
            get {
                return ResourceManager.GetString("pages.management.permissions.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users and permissions.
        /// </summary>
        internal static string pages_management_title {
            get {
                return ResourceManager.GetString("pages.management.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and manage user accounts or monitor activity..
        /// </summary>
        internal static string pages_management_users_description {
            get {
                return ResourceManager.GetString("pages.management.users.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager users.
        /// </summary>
        internal static string pages_management_users_label {
            get {
                return ResourceManager.GetString("pages.management.users.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to learn more about the application?.
        /// </summary>
        internal static string pages_more_about_description {
            get {
                return ResourceManager.GetString("pages.more.about_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string pages_more_about_link {
            get {
                return ResourceManager.GetString("pages.more.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and manage your uploaded files..
        /// </summary>
        internal static string pages_more_dashboard_description {
            get {
                return ResourceManager.GetString("pages.more.dashboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string pages_more_dashboard_link {
            get {
                return ResourceManager.GetString("pages.more.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions and user accounts..
        /// </summary>
        internal static string pages_more_management_description {
            get {
                return ResourceManager.GetString("pages.more.management_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string pages_more_management_link {
            get {
                return ResourceManager.GetString("pages.more.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about our privacy policy..
        /// </summary>
        internal static string pages_more_privacy_description {
            get {
                return ResourceManager.GetString("pages.more.privacy_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string pages_more_privacy_link {
            get {
                return ResourceManager.GetString("pages.more.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore other content that has been shared with you by other users..
        /// </summary>
        internal static string pages_more_shared_description {
            get {
                return ResourceManager.GetString("pages.more.shared_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string pages_more_shared_link {
            get {
                return ResourceManager.GetString("pages.more.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string pages_more_title {
            get {
                return ResourceManager.GetString("pages.more.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is safe with us. We are committed to protecting your personal information and using it only in accordance with our privacy policy and applicable laws. Here you will find details of how we collect, use and protect your information..
        /// </summary>
        internal static string pages_privacy_description {
            get {
                return ResourceManager.GetString("pages.privacy.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string pages_privacy_title {
            get {
                return ResourceManager.GetString("pages.privacy.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string pages_profile_contact_information_label {
            get {
                return ResourceManager.GetString("pages.profile.contact_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find and edit your personal information. Keep your contact information up to date to ensure efficient and seamless communication..
        /// </summary>
        internal static string pages_profile_description {
            get {
                return ResourceManager.GetString("pages.profile.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string pages_profile_email_label {
            get {
                return ResourceManager.GetString("pages.profile.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string pages_profile_family_name_label {
            get {
                return ResourceManager.GetString("pages.profile.family_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        internal static string pages_profile_given_name_label {
            get {
                return ResourceManager.GetString("pages.profile.given_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        internal static string pages_profile_personal_information_label {
            get {
                return ResourceManager.GetString("pages.profile.personal_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string pages_profile_phone_label {
            get {
                return ResourceManager.GetString("pages.profile.phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string pages_profile_title {
            get {
                return ResourceManager.GetString("pages.profile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pages_profile_username_label {
            get {
                return ResourceManager.GetString("pages.profile.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string pages_shared_description {
            get {
                return ResourceManager.GetString("pages.shared.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string pages_shared_download_button {
            get {
                return ResourceManager.GetString("pages.shared.download.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} download failed.
        /// </summary>
        internal static string pages_shared_download_failure {
            get {
                return ResourceManager.GetString("pages.shared.download.failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} has been completed.
        /// </summary>
        internal static string pages_shared_download_success {
            get {
                return ResourceManager.GetString("pages.shared.download.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string pages_shared_filename_label {
            get {
                return ResourceManager.GetString("pages.shared.filename_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files not found.
        /// </summary>
        internal static string pages_shared_matches_not_found {
            get {
                return ResourceManager.GetString("pages.shared.matches_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} of {all_items}.
        /// </summary>
        internal static string pages_shared_pagination_format {
            get {
                return ResourceManager.GetString("pages.shared.pagination_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string pages_shared_search_label {
            get {
                return ResourceManager.GetString("pages.shared.search_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string pages_shared_title {
            get {
                return ResourceManager.GetString("pages.shared.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        internal static string request_statuses_bad_request {
            get {
                return ResourceManager.GetString("request_statuses.bad_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been terminated by the user..
        /// </summary>
        internal static string request_statuses_client_canceled_operation {
            get {
                return ResourceManager.GetString("request_statuses.client_canceled_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the item has been denied..
        /// </summary>
        internal static string request_statuses_forbidden {
            get {
                return ResourceManager.GetString("request_statuses.forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s been an error, please try again later..
        /// </summary>
        internal static string request_statuses_internal_server_error {
            get {
                return ResourceManager.GetString("request_statuses.internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found..
        /// </summary>
        internal static string request_statuses_not_found {
            get {
                return ResourceManager.GetString("request_statuses.not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform the action or view the item..
        /// </summary>
        internal static string request_statuses_unauthorized {
            get {
                return ResourceManager.GetString("request_statuses.unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with the given name exists..
        /// </summary>
        internal static string validations_folder_name_exists {
            get {
                return ResourceManager.GetString("validations.folder_name.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File owner permission required..
        /// </summary>
        internal static string validations_permission_required {
            get {
                return ResourceManager.GetString("validations.permission.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required role name..
        /// </summary>
        internal static string validations_role_name_required {
            get {
                return ResourceManager.GetString("validations.role_name.required", resourceCulture);
            }
        }
    }
}
