//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploadify.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationDictionary_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationDictionary_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uploadify.Client.Web.Resources.TranslationDictionary.cs", typeof(TranslationDictionary_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny.
        /// </summary>
        internal static string authorization_permissions_all {
            get {
                return ResourceManager.GetString("authorization.permissions.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat soubory.
        /// </summary>
        internal static string authorization_permissions_edit_files {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat oprávnění.
        /// </summary>
        internal static string authorization_permissions_edit_permissions {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat role.
        /// </summary>
        internal static string authorization_permissions_edit_roles {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatele.
        /// </summary>
        internal static string authorization_permissions_edit_users {
            get {
                return ResourceManager.GetString("authorization.permissions.edit_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné.
        /// </summary>
        internal static string authorization_permissions_none {
            get {
                return ResourceManager.GetString("authorization.permissions.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit soubory.
        /// </summary>
        internal static string authorization_permissions_view_files {
            get {
                return ResourceManager.GetString("authorization.permissions.view_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit oprávnění.
        /// </summary>
        internal static string authorization_permissions_view_permissions {
            get {
                return ResourceManager.GetString("authorization.permissions.view_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit role.
        /// </summary>
        internal static string authorization_permissions_view_roles {
            get {
                return ResourceManager.GetString("authorization.permissions.view_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit uživatele.
        /// </summary>
        internal static string authorization_permissions_view_users {
            get {
                return ResourceManager.GetString("authorization.permissions.view_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploadify.
        /// </summary>
        internal static string common_app_name {
            get {
                return ResourceManager.GetString("common.app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Překlad nebyl nalezen..
        /// </summary>
        internal static string common_translation_not_found {
            get {
                return ResourceManager.GetString("common.translation_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string components_authenticated_layout_about_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Můj disk.
        /// </summary>
        internal static string components_authenticated_layout_dashboard_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string components_authenticated_layout_email_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celé jméno.
        /// </summary>
        internal static string components_authenticated_layout_fullname_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.fullname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string components_authenticated_layout_logout_button {
            get {
                return ResourceManager.GetString("components.authenticated_layout.logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat.
        /// </summary>
        internal static string components_authenticated_layout_management_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Více.
        /// </summary>
        internal static string components_authenticated_layout_more_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.more_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string components_authenticated_layout_privacy_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string components_authenticated_layout_profile_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string components_authenticated_layout_shared_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string components_files_dashboard_row_options_delete_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.delete_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        internal static string components_files_dashboard_row_options_detail_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.detail_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout.
        /// </summary>
        internal static string components_files_dashboard_row_options_download_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.download_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout.
        /// </summary>
        internal static string components_files_dashboard_row_options_move_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.move_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít.
        /// </summary>
        internal static string components_files_dashboard_row_options_open_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.open_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejmenovat.
        /// </summary>
        internal static string components_files_dashboard_row_options_rename_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.rename_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdílet.
        /// </summary>
        internal static string components_files_dashboard_row_options_share_link {
            get {
                return ResourceManager.GetString("components.files.dashboard_row_options.share_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vy.
        /// </summary>
        internal static string components_files_detail_contact_text {
            get {
                return ResourceManager.GetString("components.files.detail.contact_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno uživatelem.
        /// </summary>
        internal static string components_files_detail_created_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.created_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno.
        /// </summary>
        internal static string components_files_detail_date_created_label {
            get {
                return ResourceManager.GetString("components.files.detail.date_created_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naposledy změněno.
        /// </summary>
        internal static string components_files_detail_date_updated_label {
            get {
                return ResourceManager.GetString("components.files.detail.date_updated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string components_files_detail_delete_button {
            get {
                return ResourceManager.GetString("components.files.detail.delete_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stáhnout.
        /// </summary>
        internal static string components_files_detail_download_button {
            get {
                return ResourceManager.GetString("components.files.detail.download_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staženo.
        /// </summary>
        internal static string components_files_detail_download_label {
            get {
                return ResourceManager.GetString("components.files.detail.download_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Využití úložiště.
        /// </summary>
        internal static string components_files_detail_drive_size_label {
            get {
                return ResourceManager.GetString("components.files.detail.drive_size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přípona souboru.
        /// </summary>
        internal static string components_files_detail_extension_label {
            get {
                return ResourceManager.GetString("components.files.detail.extension_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název souboru.
        /// </summary>
        internal static string components_files_detail_file_name_label {
            get {
                return ResourceManager.GetString("components.files.detail.file_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soubor.
        /// </summary>
        internal static string components_files_detail_file_type_text {
            get {
                return ResourceManager.GetString("components.files.detail.file_type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet souborů.
        /// </summary>
        internal static string components_files_detail_folder_items_count_label {
            get {
                return ResourceManager.GetString("components.files.detail.folder_items_count_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název složky.
        /// </summary>
        internal static string components_files_detail_folder_name_label {
            get {
                return ResourceManager.GetString("components.files.detail.folder_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to složka.
        /// </summary>
        internal static string components_files_detail_folder_type_text {
            get {
                return ResourceManager.GetString("components.files.detail.folder_type_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umístění.
        /// </summary>
        internal static string components_files_detail_location_label {
            get {
                return ResourceManager.GetString("components.files.detail.location_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME.
        /// </summary>
        internal static string components_files_detail_mime_label {
            get {
                return ResourceManager.GetString("components.files.detail.mime_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout.
        /// </summary>
        internal static string components_files_detail_move_button {
            get {
                return ResourceManager.GetString("components.files.detail.move_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít.
        /// </summary>
        internal static string components_files_detail_open_subfolder_label {
            get {
                return ResourceManager.GetString("components.files.detail.open_subfolder_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejmenovat.
        /// </summary>
        internal static string components_files_detail_rename_button {
            get {
                return ResourceManager.GetString("components.files.detail.rename_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        internal static string components_files_detail_resource_type_label {
            get {
                return ResourceManager.GetString("components.files.detail.resource_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdílet.
        /// </summary>
        internal static string components_files_detail_share_button {
            get {
                return ResourceManager.GetString("components.files.detail.share_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno.
        /// </summary>
        internal static string components_files_detail_shared_label {
            get {
                return ResourceManager.GetString("components.files.detail.shared_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost.
        /// </summary>
        internal static string components_files_detail_size_label {
            get {
                return ResourceManager.GetString("components.files.detail.size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořil.
        /// </summary>
        internal static string components_files_detail_user_created_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.user_created_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedl.
        /// </summary>
        internal static string components_files_detail_user_updated_by_label {
            get {
                return ResourceManager.GetString("components.files.detail.user_updated_by_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string components_files_dialogs_create_name_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string components_files_dialogs_create_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat složku.
        /// </summary>
        internal static string components_files_dialogs_create_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.create.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete přesunout soubor do koše? Soubor lze po dobu 7 dní od jeho smazání obnovit, později bude změna nenávratná..
        /// </summary>
        internal static string components_files_dialogs_delete_description {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        internal static string components_files_dialogs_delete_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout složku do koše.
        /// </summary>
        internal static string components_files_dialogs_delete_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.delete.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přemístit do.
        /// </summary>
        internal static string components_files_dialogs_move_folder_select_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.folder_select_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přesunout.
        /// </summary>
        internal static string components_files_dialogs_move_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit umístnění.
        /// </summary>
        internal static string components_files_dialogs_move_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.move.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string components_files_dialogs_rename_name_label {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejmenovat.
        /// </summary>
        internal static string components_files_dialogs_rename_submit_button {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit název.
        /// </summary>
        internal static string components_files_dialogs_rename_title {
            get {
                return ResourceManager.GetString("components.files.dialogs.rename.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost souboru je příliš veliká..
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_file_too_large {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.file_too_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrání souborů je omezeno na 50 ve stejný okamžik.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_too_many_files {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.too_many_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrání souboru {0} se nezdařilo.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_uplaod_failure {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.uplaod_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrání souboru {0} bylo dokončeno.
        /// </summary>
        internal static string components_files_drag_and_drop_wrapper_uplaod_success {
            get {
                return ResourceManager.GetString("components.files.drag_and_drop_wrapper.uplaod_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidělte specifická oprávnění roli, aby jste zajistili správné fungování a bezpečnost vašeho systému. Každá role může mít různou sadu oprávnění, která definují, co mohou uživatelé s touto rolí dělat. Vyberte pouze ta oprávnění, která odpovídají odpovědnosti a potřebám dané role..
        /// </summary>
        internal static string components_permission_assignment_description {
            get {
                return ResourceManager.GetString("components.permission_assignment.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidělit oprávnění.
        /// </summary>
        internal static string components_permission_assignment_submit_button {
            get {
                return ResourceManager.GetString("components.permission_assignment.submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidělit oprávnění.
        /// </summary>
        internal static string components_permission_assignment_title {
            get {
                return ResourceManager.GetString("components.permission_assignment.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední změna.
        /// </summary>
        internal static string components_permission_dashboard_date_updated_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.date_updated_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnosti.
        /// </summary>
        internal static string components_permission_dashboard_edit_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.edit_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        internal static string components_permission_dashboard_role_detail_title {
            get {
                return ResourceManager.GetString("components.permission_dashboard.role_detail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string components_permission_dashboard_role_name_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.role_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled oprávnění.
        /// </summary>
        internal static string components_permission_dashboard_title {
            get {
                return ResourceManager.GetString("components.permission_dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnil.
        /// </summary>
        internal static string components_permission_dashboard_user_updated_by_username_label {
            get {
                return ResourceManager.GetString("components.permission_dashboard.user_updated_by.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprávnění.
        /// </summary>
        internal static string components_permission_selector_label {
            get {
                return ResourceManager.GetString("components.permission_selector.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string components_role_selector_label {
            get {
                return ResourceManager.GetString("components.role_selector.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konečně, tato disertace přezkoumá strategie pro efektivní nasazení aplikací, včetně použití moderních nástrojů a platforem jako Docker. Tímto způsobem tato bakalářská práce demonstruje, že i v rámci individuálního akademického výzkumu lze dosáhnout významného pokroku a inovace, často opomíjených ve větších, komerčně řízených projektech. Práce tak nabízí svěží a komplexní pohled na informační technologie, zdůrazňující potenciál pro hluboké odborné pochopení a praktické uplatnění teoretických znalostí..
        /// </summary>
        internal static string pages_about_sections_fifth {
            get {
                return ResourceManager.GetString("pages.about.sections.fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V dnešním proměnlivém světě informačních technologií je často pozornost soustředěna na rozsáhlé projekty vyvíjené velkými týmy. Avšak tato bakalářská práce se vydává směrem, zdůrazňujícím význam individuálního přínosu a inovace. Cílem je vytvořit projekt, který se neomezí konvenčními licenčními restrikcemi, a nabídnout místo toho řešení pod licencí typu MIT nebo lesser GNU, podporujíc tak svobodný přístup a širší aplikaci v akademické a vývojářské komunitě..
        /// </summary>
        internal static string pages_about_sections_first {
            get {
                return ResourceManager.GetString("pages.about.sections.first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvláštní pozornost je věnována také WASM, jako jednomu ze čtyř nativně podporovaných jazyků v prohlížeči, přičemž se zkoumá jeho potenciál a integrace v .NET, zejména prostřednictvím nástrojů jako Blazor. Práce dále podtrhuje význam pečlivého unit testování v .NET, což zdůrazňuje nezbytnost spolehlivosti a odolnosti softwaru..
        /// </summary>
        internal static string pages_about_sections_fourth {
            get {
                return ResourceManager.GetString("pages.about.sections.fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záměrem je rovněž prohloubit odborné znalosti a dovednosti v technologii .NET, přičemž se klade důraz na vytváření robustní struktury projektu. V rámci toho se práce zaměří na vrstvenou architekturu, zahrnující domény, data, jádro, aplikaci, RESTful API a další klíčové komponenty. Zásadní význam je přikládán bezpečnostním aspektům, včetně pokročilých metod zabezpečení jako implementace standardů OAuth2 a OpenID Connect, hashování a ověřování hesel, a obrana proti běžným bezpečnostním hrozbám, jako jsou SQL  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_second {
            get {
                return ResourceManager.GetString("pages.about.sections.second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inovace návrhových vzorů je dalším zásadním bodem, přičemž se práce neomezí na tradiční metodologie, ale začlení pokročilé vzory jako CQRS a zásady jako dependency injection, což představuje významný posun od konvenčních přístupů. V oblasti RESTful API se práce nejen zaměří na základní implementace, ale také představí OpenAPI specifikaci a zkoumá možnosti cachování dat a omezení rychlosti požadavků..
        /// </summary>
        internal static string pages_about_sections_third {
            get {
                return ResourceManager.GetString("pages.about.sections.third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string pages_about_title {
            get {
                return ResourceManager.GetString("pages.about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Můj disk.
        /// </summary>
        internal static string pages_dashboard_title {
            get {
                return ResourceManager.GetString("pages.dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o souboru.
        /// </summary>
        internal static string pages_detail_title {
            get {
                return ResourceManager.GetString("pages.detail.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednoduché a rychlé nastavení oprávnění pro vaši aplikaci..
        /// </summary>
        internal static string pages_management_description {
            get {
                return ResourceManager.GetString("pages.management.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definujte různé úrovně přístupu a přiřaďte oprávnění podle potřeby vaší aplikace..
        /// </summary>
        internal static string pages_management_permissions_description {
            get {
                return ResourceManager.GetString("pages.management.permissions.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa oprávnění.
        /// </summary>
        internal static string pages_management_permissions_label {
            get {
                return ResourceManager.GetString("pages.management.permissions.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatele a oprávnění.
        /// </summary>
        internal static string pages_management_title {
            get {
                return ResourceManager.GetString("pages.management.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházejte a spravujte uživatelské účty nebo sledujte aktivitu..
        /// </summary>
        internal static string pages_management_users_description {
            get {
                return ResourceManager.GetString("pages.management.users.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa uživatelů.
        /// </summary>
        internal static string pages_management_users_label {
            get {
                return ResourceManager.GetString("pages.management.users.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcete se dozvědět více o aplikaci?.
        /// </summary>
        internal static string pages_more_about_description {
            get {
                return ResourceManager.GetString("pages.more.about_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string pages_more_about_link {
            get {
                return ResourceManager.GetString("pages.more.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházejte a spravujte vámi nahrané soubory..
        /// </summary>
        internal static string pages_more_dashboard_description {
            get {
                return ResourceManager.GetString("pages.more.dashboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Můj disk.
        /// </summary>
        internal static string pages_more_dashboard_link {
            get {
                return ResourceManager.GetString("pages.more.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravujte oprávnění a uživatelské účty..
        /// </summary>
        internal static string pages_more_management_description {
            get {
                return ResourceManager.GetString("pages.more.management_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat.
        /// </summary>
        internal static string pages_more_management_link {
            get {
                return ResourceManager.GetString("pages.more.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přečtěte si o zásadách zpracování dat..
        /// </summary>
        internal static string pages_more_privacy_description {
            get {
                return ResourceManager.GetString("pages.more.privacy_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string pages_more_privacy_link {
            get {
                return ResourceManager.GetString("pages.more.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objevte další obsah, který vám byl zpřístupněn ostatními uživateli..
        /// </summary>
        internal static string pages_more_shared_description {
            get {
                return ResourceManager.GetString("pages.more.shared_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string pages_more_shared_link {
            get {
                return ResourceManager.GetString("pages.more.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Více.
        /// </summary>
        internal static string pages_more_title {
            get {
                return ResourceManager.GetString("pages.more.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše data jsou u nás v bezpečí. Zavazujeme se chránit vaše osobní informace a používat je pouze v souladu s našimi zásadami ochrany soukromí a platnými zákony. Zde naleznete podrobnosti o tom, jak shromažďujeme, používáme a chráníme vaše údaje..
        /// </summary>
        internal static string pages_privacy_description {
            get {
                return ResourceManager.GetString("pages.privacy.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string pages_privacy_title {
            get {
                return ResourceManager.GetString("pages.privacy.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktní údaje.
        /// </summary>
        internal static string pages_profile_contact_information_label {
            get {
                return ResourceManager.GetString("pages.profile.contact_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zde naleznete a můžete upravit své osobní informace. Udržujte své kontaktní údaje aktuální, aby byla komunikace hladká a efektivní..
        /// </summary>
        internal static string pages_profile_description {
            get {
                return ResourceManager.GetString("pages.profile.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string pages_profile_email_label {
            get {
                return ResourceManager.GetString("pages.profile.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string pages_profile_family_name_label {
            get {
                return ResourceManager.GetString("pages.profile.family_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string pages_profile_given_name_label {
            get {
                return ResourceManager.GetString("pages.profile.given_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osobní údaje.
        /// </summary>
        internal static string pages_profile_personal_information_label {
            get {
                return ResourceManager.GetString("pages.profile.personal_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string pages_profile_phone_label {
            get {
                return ResourceManager.GetString("pages.profile.phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string pages_profile_title {
            get {
                return ResourceManager.GetString("pages.profile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        internal static string pages_profile_username_label {
            get {
                return ResourceManager.GetString("pages.profile.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdílené.
        /// </summary>
        internal static string pages_shared_title {
            get {
                return ResourceManager.GetString("pages.shared.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný požadavek..
        /// </summary>
        internal static string request_statuses_bad_request {
            get {
                return ResourceManager.GetString("request_statuses.bad_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek byl ukončen uživatelem..
        /// </summary>
        internal static string request_statuses_client_canceled_operation {
            get {
                return ResourceManager.GetString("request_statuses.client_canceled_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup k položce byl zabráněn..
        /// </summary>
        internal static string request_statuses_forbidden {
            get {
                return ResourceManager.GetString("request_statuses.forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala chyba, zkuste to prosím později..
        /// </summary>
        internal static string request_statuses_internal_server_error {
            get {
                return ResourceManager.GetString("request_statuses.internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka nebyla nalezena..
        /// </summary>
        internal static string request_statuses_not_found {
            get {
                return ResourceManager.GetString("request_statuses.not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K provedení akce nebo zobrazení položky nemáte oprávnění..
        /// </summary>
        internal static string request_statuses_unauthorized {
            get {
                return ResourceManager.GetString("request_statuses.unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Složka se zvoleným jménem existuje..
        /// </summary>
        internal static string validations_folder_name_exists {
            get {
                return ResourceManager.GetString("validations.folder_name.exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyžadováno oprávnění vlastníka položky..
        /// </summary>
        internal static string validations_permission_required {
            get {
                return ResourceManager.GetString("validations.permission.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyžadován název role..
        /// </summary>
        internal static string validations_role_name_required {
            get {
                return ResourceManager.GetString("validations.role_name.required", resourceCulture);
            }
        }
    }
}
