//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploadify.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uploadify.Client.Web.Resources.TranslationDictionary", typeof(TranslationDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploadify.
        /// </summary>
        internal static string common_app_name {
            get {
                return ResourceManager.GetString("common.app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string components_authenticated_layout_about_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My files.
        /// </summary>
        internal static string components_authenticated_layout_dashboard_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string components_authenticated_layout_email_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string components_authenticated_layout_fullname_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.fullname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string components_authenticated_layout_logout_button {
            get {
                return ResourceManager.GetString("components.authenticated_layout.logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string components_authenticated_layout_management_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string components_authenticated_layout_more_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.more_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string components_authenticated_layout_privacy_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string components_authenticated_layout_profile_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string components_authenticated_layout_shared_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, this dissertation will review strategies for deploying applications effectively, including the use of modern tools and platforms such as Docker. In this way, this thesis demonstrates that even within individual academic research, significant progress and innovation can be achieved, often overlooked in larger, commercially driven projects. The thesis thus offers a fresh and comprehensive perspective on information technology, highlighting the potential for deep professional understanding and practic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_fifth {
            get {
                return ResourceManager.GetString("pages.about.sections.fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the modern, ever-changing world of information technology, attention is often directed towards large-scale projects developed by large teams. Nevertheless, this bachelor thesis takes a direction that emphasizes the significance of individual contribution and innovation. The goal is to create a project that is not constrained by conventional licensing constraints, and instead offers a solution under an MIT or lesser GNU license, encouraging free access and wider application in the academic and development [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_first {
            get {
                return ResourceManager.GetString("pages.about.sections.first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particular attention is also devoted to WASM, as one of the four natively supported languages in the browser, exploring its capabilities and integration in .NET, especially through tools such as Blazor. The work also emphasizes the significance of rigorous unit testing in .NET, highlighting the necessity of software reliability and resilience..
        /// </summary>
        internal static string pages_about_sections_fourth {
            get {
                return ResourceManager.GetString("pages.about.sections.fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose is also to deepen expertise and proficiency in .NET technology, with an emphasis on creating a robust project structure. Within this, the project will focus on layered architecture, including domains, data, core, application, RESTful APIs and other key components. Significant effort is given to security considerations, including advanced security measures such as the implementation of OAuth2 and OpenID Connect standards, password hashing and authentication, and defenses against common security t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_second {
            get {
                return ResourceManager.GetString("pages.about.sections.second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The innovation of design patterns is another crucial point, and the work will not be focused on traditional approaches, but will incorporate advanced patterns such as CQRS and patterns such as dependency injection, representing a significant departure from conventional approaches. In the area of RESTful APIs, the thesis will not only focus on fundamental implementations, but also introduce the OpenAPI specification and explore the possibilities of data caching and request rate limiting..
        /// </summary>
        internal static string pages_about_sections_third {
            get {
                return ResourceManager.GetString("pages.about.sections.third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string pages_about_title {
            get {
                return ResourceManager.GetString("pages.about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My files.
        /// </summary>
        internal static string pages_dashboard_title {
            get {
                return ResourceManager.GetString("pages.dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File details.
        /// </summary>
        internal static string pages_detail_title {
            get {
                return ResourceManager.GetString("pages.detail.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and rapid setup of permissions for your application..
        /// </summary>
        internal static string pages_management_description {
            get {
                return ResourceManager.GetString("pages.management.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define various tiers of access and assign permissions according to the requirements of your application..
        /// </summary>
        internal static string pages_management_permissions_description {
            get {
                return ResourceManager.GetString("pages.management.permissions.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions .
        /// </summary>
        internal static string pages_management_permissions_label {
            get {
                return ResourceManager.GetString("pages.management.permissions.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users and permissions.
        /// </summary>
        internal static string pages_management_title {
            get {
                return ResourceManager.GetString("pages.management.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and manage user accounts or monitor activity..
        /// </summary>
        internal static string pages_management_users_description {
            get {
                return ResourceManager.GetString("pages.management.users.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager users.
        /// </summary>
        internal static string pages_management_users_label {
            get {
                return ResourceManager.GetString("pages.management.users.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is safe with us. We are committed to protecting your personal information and using it only in accordance with our privacy policy and applicable laws. Here you will find details of how we collect, use and protect your information..
        /// </summary>
        internal static string pages_privacy_description {
            get {
                return ResourceManager.GetString("pages.privacy.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string pages_privacy_title {
            get {
                return ResourceManager.GetString("pages.privacy.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string pages_profile_contact_information_label {
            get {
                return ResourceManager.GetString("pages.profile.contact_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find and edit your personal information. Keep your contact information up to date to ensure efficient and seamless communication..
        /// </summary>
        internal static string pages_profile_description {
            get {
                return ResourceManager.GetString("pages.profile.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string pages_profile_email_label {
            get {
                return ResourceManager.GetString("pages.profile.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name.
        /// </summary>
        internal static string pages_profile_family_name_label {
            get {
                return ResourceManager.GetString("pages.profile.family_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        internal static string pages_profile_given_name_label {
            get {
                return ResourceManager.GetString("pages.profile.given_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information.
        /// </summary>
        internal static string pages_profile_personal_information_label {
            get {
                return ResourceManager.GetString("pages.profile.personal_information_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string pages_profile_phone_label {
            get {
                return ResourceManager.GetString("pages.profile.phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string pages_profile_title {
            get {
                return ResourceManager.GetString("pages.profile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string pages_profile_username_label {
            get {
                return ResourceManager.GetString("pages.profile.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string pages_shared_description {
            get {
                return ResourceManager.GetString("pages.shared.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared with me.
        /// </summary>
        internal static string pages_shared_title {
            get {
                return ResourceManager.GetString("pages.shared.title", resourceCulture);
            }
        }
    }
}
