//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uploadify.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationDictionary_cs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationDictionary_cs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uploadify.Client.Web.Resources.TranslationDictionary.cs", typeof(TranslationDictionary_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploadify.
        /// </summary>
        internal static string common_app_name {
            get {
                return ResourceManager.GetString("common.app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string components_authenticated_layout_about_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.about_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje soubory.
        /// </summary>
        internal static string components_authenticated_layout_dashboard_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.dashboard_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string components_authenticated_layout_email_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celé jméno.
        /// </summary>
        internal static string components_authenticated_layout_fullname_label {
            get {
                return ResourceManager.GetString("components.authenticated_layout.fullname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        internal static string components_authenticated_layout_logout_button {
            get {
                return ResourceManager.GetString("components.authenticated_layout.logout_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa aplikace.
        /// </summary>
        internal static string components_authenticated_layout_management_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.management_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string components_authenticated_layout_privacy_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.privacy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string components_authenticated_layout_profile_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.profile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string components_authenticated_layout_shared_link {
            get {
                return ResourceManager.GetString("components.authenticated_layout.shared_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konečně, tato disertace přezkoumá strategie pro efektivní nasazení aplikací, včetně použití moderních nástrojů a platforem jako Docker. Tímto způsobem tato bakalářská práce demonstruje, že i v rámci individuálního akademického výzkumu lze dosáhnout významného pokroku a inovace, často opomíjených ve větších, komerčně řízených projektech. Práce tak nabízí svěží a komplexní pohled na informační technologie, zdůrazňující potenciál pro hluboké odborné pochopení a praktické uplatnění teoretických znalostí..
        /// </summary>
        internal static string pages_about_sections_fifth {
            get {
                return ResourceManager.GetString("pages.about.sections.fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V dnešním proměnlivém světě informačních technologií je často pozornost soustředěna na rozsáhlé projekty vyvíjené velkými týmy. Avšak tato bakalářská práce se vydává směrem, zdůrazňujícím význam individuálního přínosu a inovace. Cílem je vytvořit projekt, který se neomezí konvenčními licenčními restrikcemi, a nabídnout místo toho řešení pod licencí typu MIT nebo lesser GNU, podporujíc tak svobodný přístup a širší aplikaci v akademické a vývojářské komunitě..
        /// </summary>
        internal static string pages_about_sections_first {
            get {
                return ResourceManager.GetString("pages.about.sections.first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvláštní pozornost je věnována také WASM, jako jednomu ze čtyř nativně podporovaných jazyků v prohlížeči, přičemž se zkoumá jeho potenciál a integrace v .NET, zejména prostřednictvím nástrojů jako Blazor. Práce dále podtrhuje význam pečlivého unit testování v .NET, což zdůrazňuje nezbytnost spolehlivosti a odolnosti softwaru..
        /// </summary>
        internal static string pages_about_sections_fourth {
            get {
                return ResourceManager.GetString("pages.about.sections.fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Záměrem je rovněž prohloubit odborné znalosti a dovednosti v technologii .NET, přičemž se klade důraz na vytváření robustní struktury projektu. V rámci toho se práce zaměří na vrstvenou architekturu, zahrnující domény, data, jádro, aplikaci, RESTful API a další klíčové komponenty. Zásadní význam je přikládán bezpečnostním aspektům, včetně pokročilých metod zabezpečení jako implementace standardů OAuth2 a OpenID Connect, hashování a ověřování hesel, a obrana proti běžným bezpečnostním hrozbám, jako jsou SQL  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pages_about_sections_second {
            get {
                return ResourceManager.GetString("pages.about.sections.second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inovace návrhových vzorů je dalším zásadním bodem, přičemž se práce neomezí na tradiční metodologie, ale začlení pokročilé vzory jako CQRS a zásady jako dependency injection, což představuje významný posun od konvenčních přístupů. V oblasti RESTful API se práce nejen zaměří na základní implementace, ale také představí OpenAPI specifikaci a zkoumá možnosti cachování dat a omezení rychlosti požadavků..
        /// </summary>
        internal static string pages_about_sections_third {
            get {
                return ResourceManager.GetString("pages.about.sections.third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string pages_about_title {
            get {
                return ResourceManager.GetString("pages.about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje soubory.
        /// </summary>
        internal static string pages_dashboard_title {
            get {
                return ResourceManager.GetString("pages.dashboard.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o souboru.
        /// </summary>
        internal static string pages_detail_title {
            get {
                return ResourceManager.GetString("pages.detail.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednoduché a rychlé nastavení oprávnění pro vaši aplikaci..
        /// </summary>
        internal static string pages_management_description {
            get {
                return ResourceManager.GetString("pages.management.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definujte různé úrovně přístupu a přiřaďte oprávnění podle potřeby vaší aplikace..
        /// </summary>
        internal static string pages_management_permissions_description {
            get {
                return ResourceManager.GetString("pages.management.permissions.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa oprávnění.
        /// </summary>
        internal static string pages_management_permissions_label {
            get {
                return ResourceManager.GetString("pages.management.permissions.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravovat uživatele a oprávnění.
        /// </summary>
        internal static string pages_management_title {
            get {
                return ResourceManager.GetString("pages.management.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procházejte a spravujte uživatelské účty nebo sledujte aktivitu..
        /// </summary>
        internal static string pages_management_users_description {
            get {
                return ResourceManager.GetString("pages.management.users.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa uživatelů.
        /// </summary>
        internal static string pages_management_users_label {
            get {
                return ResourceManager.GetString("pages.management.users.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše data jsou u nás v bezpečí. Zavazujeme se chránit vaše osobní informace a používat je pouze v souladu s našimi zásadami ochrany soukromí a platnými zákony. Zde naleznete podrobnosti o tom, jak shromažďujeme, používáme a chráníme vaše údaje..
        /// </summary>
        internal static string pages_privacy_description {
            get {
                return ResourceManager.GetString("pages.privacy.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromí.
        /// </summary>
        internal static string pages_privacy_title {
            get {
                return ResourceManager.GetString("pages.privacy.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zde naleznete a můžete upravit své osobní informace. Udržujte své kontaktní údaje aktuální, aby byla komunikace hladká a efektivní..
        /// </summary>
        internal static string pages_profile_description {
            get {
                return ResourceManager.GetString("pages.profile.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string pages_profile_email_label {
            get {
                return ResourceManager.GetString("pages.profile.email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        internal static string pages_profile_family_name_label {
            get {
                return ResourceManager.GetString("pages.profile.family_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        internal static string pages_profile_given_name_label {
            get {
                return ResourceManager.GetString("pages.profile.given_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string pages_profile_phone_label {
            get {
                return ResourceManager.GetString("pages.profile.phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string pages_profile_title {
            get {
                return ResourceManager.GetString("pages.profile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        internal static string pages_profile_username_label {
            get {
                return ResourceManager.GetString("pages.profile.username_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sdíleno se mnou.
        /// </summary>
        internal static string pages_shared_title {
            get {
                return ResourceManager.GetString("pages.shared.title", resourceCulture);
            }
        }
    }
}
